### ISSUE TITLE
Build CI/CD Pipeline

### ISSUE THREAD

**Issue by y1hongju** [dre4m1ng/spring-of-fifa#10]
## Description

프로젝트에 적용할 CI/CD 파이프라인을 GitHub Actions를 활용하여 구축합니다.

### CI

Pylint를 사용하여 코드 린팅을 진행합니다. 향후 모듈 테스트나 타입 체킹 등의 작업으로 확장할 수 있습니다.

+) autopep8을 사용하여 코드 포매팅 테스트도 진행하며 테스트가 실패한 경우 CI 테스팅이 실패한 것으로 간주합니다.

### CD

향후 Flask를 활용해 개발용 웹 서버를 구축하고 내부에서 사용되는 웹 서비스를 배포합니다. 이후 main 브랜치에 merge 되는 코드들을 자동으로 해당 서버가 배포하도록 하는 CD 파이프라인을 구축합니다.

### Local Environment

- [x] #13 
- [x] #15

### GitHub Actions Environment

- [x] #17

**Comment by je0nh** [comment]
- 참고 자료
[GitHub Action 설명](https://medium.com/@jjj3055/github-action%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-ci-cd-%EA%B5%AC%EC%B6%95%EA%B8%B0-f0aa9c1a9c52)

**Comment by y1hongju** [comment]
TODO의 `기존 파이썬 코드에 autopep8을 적용`을 다음 커맨드로 해결하였다. `autopep8 --aggressive --aggressive --recursive --in-place .`

**Comment by y1hongju** [comment]
configuration에 `pyproject.toml`을 사용해야 하는 이유 [링크](https://www.reddit.com/r/learnpython/comments/yqq551/comment/ivpl7rj/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

**Comment by y1hongju** [comment]
TODO의 ` 기존 자바스크립트, HTML, CSS, 마크다운 등의 코드에 ESLint, Prettier 적용` 작업 진행할 예정입니다.

**Comment by je0nh** [comment]
# CI pipeline
- [GitHub Action Checkout](https://www.daleseo.com/github-actions-checkout/)
    - Repo code를 다운받음
      ```yaml
      name: Automatically Integration
      
      on: [push]
      
      jobs:
        checkout:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v3
            - run: ls -al
      ```
    
        ![Screenshot 2024-02-19 at 6 01 57 PM](https://github.com/dre4m1ng/spring-of-fifa/assets/145730125/52988f37-a7e7-4959-8fda-596e736d7d3e)


- Discord 알림
    - [Webhook](https://velog.io/@nathan29849/Discord-Bot-%EB%A7%8C%EB%93%A4%EA%B8%B0%EB%A9%8B%EC%9F%81%EC%9D%B4-%EC%82%AC%EC%9E%90%EC%B2%98%EB%9F%BC-%EC%97%B0%ED%95%A9%EC%84%B8%EC%85%98)
    Repo에 PR한 코드를 GitHub Action을 통해 autopep8, pylint 작업을 수행후 결과를 Discord Webhook를 사용해서 Discord로 결과 전달
      ```yaml
      name: Automatic Integration
      
      on: [push]
      
      jobs:
        check-out:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout code
              uses: actions/checkout@v3
      
            - name: Install requirements package
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
      
            - name: pep8, pylint testing
              run: |
                autopep8 test.py
                pylint test.py
      
            - name: Generate Environment Variables File
              run: |
                echo "DISCORD_WEBHOOK=$DISCORD_WEBHOOK" >> .env
              env:
                DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
            
            - name: Send build status to Discord
              if: success()
              run: |
                curl -X POST -H "Content-Type: application/json" -d '{"content":"Build succeeded!"}' ${{ secrets.DISCORD_WEBHOOK }}
        
            - name: Send pylint output to Discord on failure
              if: failure()
              run: |
                pylint test.py > pylint_output.txt || true
                pylint_output=$(cat pylint_output.txt)
                json='{"content":"'"$pylint_output"'"}'
                curl -X POST -H "Content-Type: application/json" -d '{"content":"Build failed!"}' ${{ secrets.DISCORD_WEBHOOK }}
                echo $json | curl -X POST -H "Content-Type: application/json" -d @- ${{ secrets.DISCORD_WEBHOOK }}
              continue-on-error: true
      ```
        <img width="400" alt="Screenshot 2024-02-22 at 5 13 18 PM" src="https://github.com/dre4m1ng/spring-of-fifa/assets/145730125/60797d2c-b4f0-41f0-80d0-901776a203f5">
